# get namespace Info
GET http://190.216.224.11:3000/blocks/{height}/limit/{limit}
Content-Type: application/json
Accept: */*
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15
Cache-Control: no-cache

###

GET http://190.216.224.11:3000/chain/height
Content-Type: application/json
Accept: */*
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15
Cache-Control: no-cache

####

GET http://190.216.224.11:3000/block/1
Content-Type: application/json
Accept: */*
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15
Cache-Control: no-cache

####

GET http://190.216.224.11:3000/block/1/transactions
Content-Type: application/json
Accept: */*
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15
Cache-Control: no-cache

####

GET http://190.216.224.11:3000/diagnostic/storage
Content-Type: application/json
Accept: */*
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15
Cache-Control: no-cache

####

GET http://190.216.224.11:3000/blocks/height
Content-Type: application/json
Accept: */*
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15
Cache-Control: no-cache

####