# get mosaicIds name for next test request
POST http://catapult.internal.proximax.io:3000/mosaic/names
Content-Type: application/json
Accept: */*
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15
Cache-Control: no-cache

{
  "mosaicIds": [
    "d525ad41d95fcf29"
  ]
}

####
# get mosaicIds name for next test request
POST http://catapult.internal.proximax.io:3000/mosaic
Content-Type: application/json
Accept: */*
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15
Cache-Control: no-cache

{
  "mosaicIds": [
    "d525ad41d95fcf29"
  ]
}

####

# get namespace Info
GET http://catapult.internal.proximax.io:3000/mosaic/d525ad41d95fcf29
Content-Type: application/json
Accept: */*
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15
Cache-Control: no-cache

###

#get namespace Info from Account -return empty array - what??
GET http://catapult.internal.proximax.io:3000/namespace/84b3552d375ffa4b/mosaics?id=3646934825&pagesize=32
Content-Type: application/json
Accept: */*
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15
Cache-Control: no-cache


###